import { ScrollView, StyleSheet } from 'react-native';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';

// Kept in sync by hand with legal/TERMS_OF_SERVICE.md - see that file's
// header for why (review-copy banner vs. clean end-user rendering here).
export default function TermsOfServiceScreen() {
  return (
    <ThemedView style={styles.container}>
      <ScrollView contentContainerStyle={styles.content}>
        <ThemedText type="title" style={styles.title}>Terms of Service</ThemedText>
        <ThemedText style={styles.meta}>Last updated: [date]</ThemedText>

        <ThemedText style={styles.paragraph}>
          By using Lightbulb (the &quot;App&quot;), you agree to these terms. If you don&apos;t
          agree, please don&apos;t use the App.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>What Lightbulb does</ThemedText>
        <ThemedText style={styles.paragraph}>
          Lightbulb aggregates news headlines from public RSS feeds and offers an optional
          &quot;Illuminate&quot; feature that uses an AI model to generate a short explanation of a
          headline&apos;s context, optionally tailored to preferences you set. See our{' '}
          Privacy Policy for how that works.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>AI-generated content — no warranty on accuracy</ThemedText>
        <ThemedText style={styles.paragraph}>
          Illuminate&apos;s explanations are generated by an AI model and may be incomplete, out of
          date, or factually incorrect. They&apos;re provided for general informational purposes
          only and aren&apos;t a substitute for reading the original article. Verify anything
          important against the original source.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>Third-party content and links</ThemedText>
        <ThemedText style={styles.paragraph}>
          Article cards and Illuminate explanations link to third-party news publishers. We
          don&apos;t control, endorse, or take responsibility for the content, accuracy, or
          availability of any third-party site you reach through the App.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>Acceptable use</ThemedText>
        <ThemedText style={styles.paragraph}>
          Don&apos;t use the App for any unlawful purpose, attempt to circumvent rate limits or
          reverse-engineer the App&apos;s backend, or abuse the Illuminate feature in a way that
          imposes unreasonable cost or load on our infrastructure.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>No guaranteed availability</ThemedText>
        <ThemedText style={styles.paragraph}>
          We don&apos;t guarantee the App, any particular news source, or the Illuminate feature
          will be available at all times — news feeds and the underlying AI provider are
          third-party services outside our control.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>Disclaimer &amp; limitation of liability</ThemedText>
        <ThemedText style={styles.paragraph}>
          The App is provided &quot;as is&quot; and &quot;as available,&quot; without warranties of
          any kind. To the maximum extent permitted by law, we are not liable for any indirect,
          incidental, or consequential damages arising from your use of the App, including reliance
          on any AI-generated explanation.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>Changes</ThemedText>
        <ThemedText style={styles.paragraph}>
          We may update the App or these terms at any time. Material changes will be reflected in
          the &quot;Last updated&quot; date above.
        </ThemedText>

        <ThemedText type="subtitle" style={styles.heading}>Contact us</ThemedText>
        <ThemedText style={styles.paragraph}>
          Questions about these terms: [contact email]
        </ThemedText>
      </ScrollView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 60,
  },
  title: {
    marginBottom: 4,
  },
  meta: {
    fontSize: 13,
    opacity: 0.6,
    marginBottom: 20,
  },
  heading: {
    marginTop: 20,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 15,
    lineHeight: 22,
    opacity: 0.9,
    marginBottom: 8,
  },
});
